// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIDemo.Data;

#nullable disable

namespace WebAPIDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDemo.Models.CustomValidations.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "PUMA",
                            Color = "Blue",
                            Gender = "Men",
                            Price = 2000.0,
                            Size = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "NIKE",
                            Color = "Green",
                            Gender = "Women",
                            Price = 3000.0,
                            Size = 7
                        },
                        new
                        {
                            Id = 3,
                            Brand = "PUMA",
                            Color = "Yellow",
                            Gender = "Men",
                            Price = 4000.0,
                            Size = 9
                        },
                        new
                        {
                            Id = 4,
                            Brand = "NIKE",
                            Color = "Red",
                            Gender = "Women",
                            Price = 5000.0,
                            Size = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
